using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Configuration;
using System.Data.SqlClient;
using DevExpress.Data;
using DevExpress.XtraEditors;
namespace Husnain
{

    

    public partial class MainForm : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public MainForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
         
        }

        private void connections(string StrCMD)
        {
            

        }



        private void MainForm_Load(object sender, EventArgs e)
        {
            PosDataFile_DataDataContext dbContext = new PosDataFile_DataDataContext();
            //try
            //{
            //    FMCreditSaleInvoiceEdit form = new FMCreditSaleInvoiceEdit();
            //    form.MdiParent = this;
            //    form.Show();
            //}
            //catch (Exception ex)
            //{
            //    GeneralAlerts.RedefinedExceptions(ex);
            //}
             
        }

        private void BBIBrand_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

            try
            {
                BrandRegistration form = new BrandRegistration();
             //   form.MdiParent = this;
                form.ShowDialog();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {


        }

        private void gridView1_CustomUnboundColumnData(object sender, DevExpress.XtraGrid.Views.Base.CustomColumnDataEventArgs e)
        {
            try
            {
                if (e.Column.Name == "Sr")
                {
                    e.Value = e.ListSourceRowIndex + 1;
                }
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }

        private void BBICategoryRegistration_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                BrandsCategories form = new BrandsCategories();
                //   form.MdiParent = this;
                form.ShowDialog();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }

        private void CreditPurchaseWithParties_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

            try
            {
                FMPurchaseInvoice form = new FMPurchaseInvoice();
                form.MdiParent = this;
                form.Term = PublicFunctions.CreditTerm;
                form.Show();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }

        private void CashPurchaseWithParties_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

            try
            {
                FMPurchaseInvoice form = new FMPurchaseInvoice();
                form.MdiParent = this;
                form.Term = PublicFunctions.CashTerm;
                form.Text = "Cash Purchase";
                form.Show();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }
        private void CreditSaleWithParties_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

            try
            {
                FMCreditSaleInvoice form = new FMCreditSaleInvoice();
                form.MdiParent = this;
                form.Term = PublicFunctions.CreditTerm;
                form.Show();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }
        private void CashSaleWithParties_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

            try
            {
                FMCreditSaleInvoice form = new FMCreditSaleInvoice();
                form.MdiParent = this;
                form.Term = PublicFunctions.CashTerm;
                form.txtWalkingName.Visible = false;
                form.lbPhoneNo.Visible = false;
                form.Text = "Cash Sale";
                form.Show();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }

        private void CashSaleWithWalkingCustomer_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

            try
            {
                FMCreditSaleInvoice form = new FMCreditSaleInvoice();
                form.MdiParent = this;
                form.Term = PublicFunctions.CashTerm;
                form.LPTo.Visible = false;
                form.txtWalkingName.Visible = true;
                form.txtWalkingName.Size = new Size(694, 20);
                form.txtWalkingName.Location = new Point(87, 27);
                
                form.txtPhoneNo.Visible = true;
                form.lbPhoneNo.Visible = true; 
                
                

                form.Text = "Cash Sale Walk-In Customer";
                form.Show();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }

        

        private void BBIProductRegistration_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                BrandsCategoriesProducts form = new BrandsCategoriesProducts();
                //   form.MdiParent = this;
                form.ShowDialog();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }

        private void BBIProductsGroups_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

            try
            {
                BrandsProductsGroups form = new BrandsProductsGroups();
                //   form.MdiParent = this;
                form.ShowDialog();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }

        private void BBIVouchers_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                FMAccountsVouchersRec form = new FMAccountsVouchersRec();
   

                //   form.MdiParent = this;
                form.ShowDialog();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }

        private void BBIGeneralLedger_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {

                GeneralLedger form = new GeneralLedger();
                form.MdiParent = this;
                form.Show();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }

        private void BBIExpenses_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                FMExpense form = new FMExpense();
                form.MdiParent = this;
                form.Show();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }

        private void BBIAccountHead_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                FMAccountsHead form = new FMAccountsHead();

                form.ShowDialog();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }

        private void BBIAccounts_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                FMAccountsDetails form = new FMAccountsDetails();
                
                form.ShowDialog();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }

        private void BBIPurchInvoiceEdit_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            
        }

        private void CreditSaleWithPartiesReturn_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                FMCreditSaleInvoiceReturn form = new FMCreditSaleInvoiceReturn();
                form.MdiParent = this;
                form.Term = PublicFunctions.CreditTerm;
                form.Show();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }


        private void CashSaleWithPartiesReturn_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                FMCreditSaleInvoiceReturn form = new FMCreditSaleInvoiceReturn();
                form.MdiParent = this;
                form.Text = "Cash Sale Return";
                form.Term = PublicFunctions.CashTerm;
                form.Show();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }
        private void CashSaleWithWalkingCustomerReturn_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                FMCreditSaleInvoiceReturn form = new FMCreditSaleInvoiceReturn();
                form.MdiParent = this;
                form.Text = "Cash Sale Return (Walking Customer)";
                form.Term = PublicFunctions.CashTerm;
                
                //form.txtWalkingName.Size = new Size(694, 20);
                //form.txtWalkingName.Location = new Point(87, 27);
                form.txtWalkingName.Visible = true;
                form.txtWalkingName.Size = form.LPTo.Size;
                form.txtWalkingName.Location = form.LPTo.Location;
                form.txtPhoneNo.Visible = true;
                form.lbPhoneNo.Visible = true;
                form.WalkIn = true;
                form.LPTo.Visible = false;

                form.Show();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }
        //CashSaleWithWalkingCustomer_ItemClick
        private void BBIVouchersPaying_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                FMAccountsVouchersPay form = new FMAccountsVouchersPay();


                //   form.MdiParent = this;
                form.ShowDialog();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }

        private void CreditPurchaseWithPartiesReturn_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                FMPurchaseInvoiceReturn form = new FMPurchaseInvoiceReturn();
                form.MdiParent = this;
                form.Show();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }

        private void  CashPurchaseWithPartiesReturn_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                FMPurchaseInvoiceReturn form = new FMPurchaseInvoiceReturn();
                form.MdiParent = this;
                form.Text = "Cash Purchase Return";
                form.Term = PublicFunctions.CashTerm;
                form.Show();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }

        private void BBIIncomingStock_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                FMIncommingStock form = new FMIncommingStock();
                //   form.MdiParent = this;
                form.ShowDialog();
            }
            catch (Exception ex)
            {
                GeneralAlerts.RedefinedExceptions(ex);
            }
        }

       

        //private void simpleButton1_Click(object sender, EventArgs e)
        //{
        //    try
        //    {
        //        //PublicFunctions.Connecting("select * from Brand", gridControl1);
        //        //this is using general query
        //        //using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["DBCS"].ConnectionString))
        //        //{
        //        //    SqlDataAdapter da = new SqlDataAdapter("select ('BR-'+cast(B.BrandId as nvarchar(20))) as a, B.BrandName+'\'+BC.BrandCat as BrandCate from Brand as B inner join Brand_Category as BC on B.BrandId = BC.BrandId", con);

        //        //    DataSet ds = new DataSet();
        //        //    da.Fill(ds, "Brand_Category");
        //        //    DataTable dt = (ds).Tables["Brand_Category"];

        //        //    gridControl1.DataSource = dt;
        //        //    searchLookUpEdit1.Properties.DisplayMember = dt.Columns["BrandCate"].ToString();
        //        //    searchLookUpEdit1.Properties.ValueMember = dt.Columns["a"].ToString();
        //        //    searchLookUpEdit1.Properties.DataSource = dt;



        //        //}


        //        // This is code for Stored Procedures

        //using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["DBCS"].ConnectionString))
        //{
        //    SqlCommand cmd = new SqlCommand("spGetBrand", con);
        //    cmd.CommandType = System.Data.CommandType.StoredProcedure;
        //    cmd.Parameters.Add("@id", 5);
        //    SqlDataAdapter da = new SqlDataAdapter(cmd);

        //    DataSet ds = new DataSet();
        //    da.Fill(ds, "Brand");
        //    DataTable dt = (ds).Tables["Brand"];

        //    gridControl1.DataSource = dt;
        //    searchLookUpEdit1.Properties.DisplayMember = dt.Columns["BrandName"].ToString();
        //    searchLookUpEdit1.Properties.ValueMember = dt.Columns["BrandId"].ToString();
        //    searchLookUpEdit1.Properties.DataSource = dt;



        }
        //       // for inserting data into table
        //        using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["DBCS"].ConnectionString))
        //        {
        //            con.Open();
        //            SqlCommand cmd = new SqlCommand("Delete Brand where BrandId = 2", con);
        //            cmd.ExecuteNonQuery();
        //            MessageBox.Show("record entered");
        //            //SqlDataAdapter da = new SqlDataAdapter(cmd);

        //            //DataSet ds = new DataSet();
        //            //da.Fill(ds, "Brand");
        //            //DataTable dt = (ds).Tables["Brand"];

        //            //gridControl1.DataSource = dt;
        //            //searchLookUpEdit1.Properties.DisplayMember = dt.Columns["BrandName"].ToString();
        //            //searchLookUpEdit1.Properties.ValueMember = dt.Columns["BrandId"].ToString();
        //            //searchLookUpEdit1.Properties.DataSource = dt;



        //        }

        //    }
        //    catch (Exception ex)
        //    {

        //    }
                        
            
            
        //}
    }